[package]
name = "cohen"
version = "0.1.0"
authors = ["Inumidun <ashamao90@gmnail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
